// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmmPq9N8IuzTrisPaRoe3xcDpcoDGqEk',
    appId: '1:994117346733:web:d7d8c9efffb03453f16d24',
    messagingSenderId: '994117346733',
    projectId: 'sk-kitchen',
    authDomain: 'sk-kitchen.firebaseapp.com',
    storageBucket: 'sk-kitchen.appspot.com',
    measurementId: 'G-VFZN6VDVXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr41g984nOtlXDKAvblHe81-j8C5AyOlY',
    appId: '1:994117346733:android:0f341a55de9eec1ff16d24',
    messagingSenderId: '994117346733',
    projectId: 'sk-kitchen',
    storageBucket: 'sk-kitchen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC89DLOtfvkUz2aln8uxuLEYJ_d34qJqEw',
    appId: '1:994117346733:ios:e7b3fdb9d8a2aa95f16d24',
    messagingSenderId: '994117346733',
    projectId: 'sk-kitchen',
    storageBucket: 'sk-kitchen.appspot.com',
    iosBundleId: 'com.example.skKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC89DLOtfvkUz2aln8uxuLEYJ_d34qJqEw',
    appId: '1:994117346733:ios:e7b3fdb9d8a2aa95f16d24',
    messagingSenderId: '994117346733',
    projectId: 'sk-kitchen',
    storageBucket: 'sk-kitchen.appspot.com',
    iosBundleId: 'com.example.skKitchen',
  );
}
